# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello']

# Cell
def say_hello(to):
    "Say hello to somebody"
    print('Hello {0}'.format(to))
    return
    #return f'Hello {to}!'